export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 className="text-stone-500">Header</h1>
        </header>
        {children}
        <footer>
          <h1 className="bg-red-200">This is a footer</h1>
        </footer>
      </body>
    </html>
  );
}
